jwt:
  time: 90000
  secret: hello-world1234444
posco:
  name: 3기5555555
  count: 205555555
  datasource:
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: "{cipher}37acba01b24a74db532855cff8787b842ee57e9a0981d11d45c408c2082eb267"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: "{cipher}37acba01b24a74db532855cff8787b842ee57e9a0981d11d45c408c2082eb267"
