jwt:
  time: 90000
  secret: hello-world1234444
posco:
  name: 3기5555555
  count: 205555555
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
