jwt:
  time: 905325235
  secret: hello-world235235325
posco:
  name: 3235235235기
  count: 2135235235
test:
  datasource:
    url: jdbc:mysql://?.?.?.?:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: rollin
    password: 1234
