posco:
  name: "{cipher}be36399465211a544bf2b6a9f2846a19166f0f6e1c87c78a2489c7d88e6835d3"
  count: 20
jwt:
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime: 86400000 # 3600000(1시간) * 24
  # xpTime : 30000 # 30초
